default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] || ENV["DATABASE_PRIVATE_URL"] %>

development:
  <<: *default
  database: ascend_api_development

test:
  <<: *default
  database: ascend_api_test

production:
  <<: *default
