production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  cleanup_expired_sessions:
    command: "Session.where('expires_at < ?', Time.current).delete_all"
    schedule: every day at 3am

  cleanup_orphaned_blobs:
    command: "ActiveStorage::Blob.unattached.where('created_at < ?', 1.day.ago).find_each(&:purge_later)"
    schedule: every day at 4am
